#! /bin/sh

# optinal: feh for background image
# feh --bg-fill ~/Pictures/grey.png

# optinal: polybar & polybar-themes for status bar
# $HOME/.config/polybar/launch.sh --forest

sxhkd &
# optinal: picom for blur & rounded corner
# picom --experimental-backends &

bspc monitor -d I II III IV V VI

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color '#373737'
bspc config normal_border_color '#1B1A17'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# unknown stuff
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
